/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobovee_plugin_pluginmgr_DyJniProxy */

#ifndef _Included_com_mobovee_plugin_pluginmgr_DyJniProxy
#define _Included_com_mobovee_plugin_pluginmgr_DyJniProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobovee_plugin_pluginmgr_DyJniProxy
 * Method:    OnClearClassLoader
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mobovee_plugin_pluginmgr_DyJniProxy_OnClearClassLoader
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
